# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: blogpost
  pool: 5
  username: <%= Rails.application.secrets[:mysql_user] %>
  password: <%= Rails.application.secrets[:mysql_pass] %>
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: blogpost
  pool: 5
  username: <%= Rails.application.secrets[:mysql_user] %>
  password: <%= Rails.application.secrets[:mysql_pass] %>

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: blogpost
  pool: 5
  username: <%= Rails.application.secrets[:mysql_user] %>
  password: <%= Rails.application.secrets[:mysql_pass] %>
