# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: blogpost
  pool: 5
  username: root
  password: ilovemyself
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: blogpost
  pool: 5
  username: root
  password: ilovemyself

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: blogpost
  pool: 5
  username: root
  password: ilovemyself
